info:
  app:
    name: &name Eveline ERP
    decription: Backend application for Eveline ERP UI.
    version: 1.1.0

server:
  port: 8080
  servlet:
    context-path: /eveline-erp
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
  tomcat:
    basedir: ./tomcat
    accesslog:
      enabled: true
      prefix: access_log
      buffered: false
      pattern: "%a | %{yyyy-MM-dd'T'HH:mm:ss.SSSZ}t | \"%r\" | %s | %D ms | %{Content-Length}i | %B | %{X-Forwarded-For}i | %{X-FFD-TAG}i | %{User-Agent}i"
      file-date-format:
      max-days: 10
      rotate: true
    max-threads: 100
    min-spare-threads: 3
    accept-count: 100

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: *name
  boot:
    admin:
      context-path: sba
      client:
        url: http://localhost:8080/eveline-erp/sba
        username: "admin"                  #These two are needed so that the client
        password: "26AROUNDyearSOFT4411"   #can register at the protected server api
        instance:
          metadata:
            user.name: "admin"                    #These two are needed so that the server
            user.password: "26AROUNDyearSOFT4411" #can access the protected client endpoints
        period: 300000
      monitor:
        status-interval: 300000
        status-lifetime: 300000
      ui:
        brand: '<img src="assets/img/icon-spring-boot-admin.svg"><span>Eveline ERP</span>'
        title: "Eveline ERP"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/evelinedb"
    username: "eveline-erp"
    password: "TEwZn;V#3?roLBA6i=2pw8Zo"
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 3 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
      pool-name: "EvelineDBPool"
  jmx:
    enabled: true
  jpa:
    database: postgresql
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
    show-sql: true
  security:
    user:
      name: "admin"
      password: "26AROUNDyearSOFT4411"
